_BASE_: "../Base_rec.yaml"

MODEL:
  WEIGHTS: "output/R50/150k_tt_mlt_13_15_textocr/pretrain/model_final.pth"
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.3

DATASETS:
  TRAIN: ("ic15_train",)
  TEST: ("ic15_test",)

INPUT:
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 1900
  # ROTATE: False

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (100000,)  # no step
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000
  # 1 - Generic, 2 - Weak, 3 - Strong (for icdar2015)
  LEXICON_TYPE: 1

OUTPUT_DIR: "output/R50/ArT/pretrain/ic15_art_imgsize_generic"